src/Models/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Estoque_Rodrigo.Models
{
    public class UserViewModel : ContactViewModel
    {
        public int ParentId { get; set; }
 
        [Display(Name = "User ID")]
        public string UserID { get; set; }

        [DataType(DataType.Senha)]
        public string Senha { get; set; }

        [DataType(DataType.Senha)]
        [Display(Name = "Confirmar Senha")]
        public string RepetirSenha { get; set; }

    }

    public class LoginModel
    {
        [Required]
        [Display(Nome = "User ID")]
        public string UserID { get; set; }

        [Required]
        [DataType(DataType.Senha)]
        public string Senha { get; set; }
        [Display(Name = "Lembrar-me")]
        public bool Lembrarme { get; set; }

    }
}

src/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ABC_Inventory;
using ABC_Inventory.Models;
using ClientDB;
namespace Estoque_Rodrigo.Controllers
{
    public class ClientsController : Controller
    {

        private Estoque_RodrigoEntities1 db = new Estoque_RodrigoClientEntities1(); 
        
       
        // GET: Clients
        public ActionResult Index()
        {
            
            return View(db.Clients.ToList());
        }

       
        //--------------------------------------------------------------------------------------------------
        public ActionResult RegisterView(int? Id)
        {
            ClientViewModel clientview = new ClientViewModel();
            var comptypes = from Business_Types c in Enum.GetValues(typeof(Business_Types))
                            select new { ID = (int)c, Name = c.ToString() };

           if (Id != null)
            {
                Client client = db.Clients.Find(Id);

                if (client != null)
                {
                    clientview.Clientname = client.Clientname;
                    clientview.Description = client.Description;
                    clientview.CageCode = client.CageCode;
                    clientview.SICCode = client.SICCode;
                    clientview.InActive = (client.InActive == false) ? false : (bool) client.InActive;
                    Address address = client.Addresses.FirstOrDefault();
                    if (address != null)
                    {
                        clientview.Address1 = address.Address1;
                        clientview.Address2 = address.Address2;
                        clientview.City = address.City;
                        clientview.State = address.State;
                        clientview.PostalCode = address.PostalCode;
                        clientview.Province = address.Province;
                        clientview.Country = address.Country;
                    }
                }
                ViewBag.Title = "Edit Client Information";
                
                ViewBag.CompanyType = new SelectList(comptypes,"ID", "Nome", (int)client.CompanyType.Value);
            }
           else
           {
               ViewBag.Title = "Registrar Novo Cliente";
               ViewBag.CompanyType = new SelectList(comptypes, "ID", "Nome");
           }
            return View(clientview);
        }

        [HttpPost]
        public ActionResult RegisterView(ClientViewModel clientview)
        {
             if (ModelState.IsValid)
            {
                int id = clientview.Id;
                Session["ParentId"] = id.ToString();
                Update_Client(clientview);

                if (clientview.Id == 0) 
                    return RedirectToAction("UserView");
            }
            return View(clientview);
        }

        [HttpGet]
        public ActionResult ClientProfile()
        {
            ClientViewModel clientview = new ClientViewModel();
            ActiveUser AU = (ActiveUser)Session["ActiveUser"];
            Client client = (from c in db.Clients
                             where c.Id == AU.ClientId
                             select c).FirstOrDefault();
            clientview.Id = client.Id;
            clientview.Description = client.Description;
            clientview.Clientname = client.Clientname;
            clientview.CageCode = client.CageCode;
            clientview.SICCode = client.SICCode;
            clientview.CompanyType = (Business_Types) client.CompanyType;
            Option opt = client.Options.FirstOrDefault();
            clientview.Purchasing = (bool)opt.Purchasing;
            clientview.Sales = (bool)opt.Sales;
            clientview.Warehouse = (bool)opt.Warehouse;
            Address addr = client.Addresses.FirstOrDefault();
            Common.CopyProperties(addr, clientview, false);
            return View(clientview);
        }

        [HttpPost]
        public ActionResult ClientProfile(ClientViewModel clientview)
        {

            return View(clientview);
        }

        public void Update_Client(ClientViewModel clientview)
        {
           Client client;
            client = (clientview.Id > 0) ? db.Clients.Find(clientview.Id) :  client = new Client();

            client.Clientname = clientview.Clientname;
            client.Description = clientview.Description;
            client.CageCode = clientview.CageCode;
            client.SICCode = clientview.SICCode;
            client.CompanyType = clientview.CompanyType;
            if (client.Status == null)
                client.Status = "DEMO";
            client.ExpDate = DateTime.Now.AddMonths(1);
            Address address;
 
            address = (clientview.Id > 0) ? client.Addresses.FirstOrDefault() : new Address();
                
            address.Address1 = clientview.Address1;
            address.Address2 = clientview.Address2;
            address.City = clientview.City;
            address.State = clientview.State;
            address.PostalCode = clientview.PostalCode;
            address.Province = clientview.Province;
            address.Country = clientview.Country;
            address.AddressType = Address_Types.Corporate;
            Option opts;
            opts = (clientview.Id > 0) ? client.Options.FirstOrDefault() : new Option();
            opts.Item = true;
            opts.Purchasing = clientview.Purchasing;
            opts.Sales = clientview.Sales;
            opts.Warehouse = clientview.Warehouse;

            if (clientview.Id > 0)
            {
                db.Entry(address).State = EntityState.Modified;
                db.Entry(client).State = EntityState.Modified;
                db.Entry(opts).State = EntityState.Modified;
             }
            else
            {
                License lic =  new License();
                lic.Maximum_Installs = 1;
                lic.Current_Installs = 0;
                lic.Cost = 0;
                lic.Period = 0;
                lic.DueDate = DateTime.Now.AddMonths(1);
                lic.ProductKey = Guid.NewGuid().ToString();
                client.Licenses.Add(lic);
                client.Addresses.Add(address);
                opts.Demo = true;
                opts.ExpDate = DateTime.Now.AddMonths(1);
                client.Options.Add(opts);
                db.Clients.Add(client);
            }

 
            try
            {
                db.SaveChanges();
                Session["ParentId"] = client.Id.ToString();
            }
            catch (DbEntityValidationException e)
            {
                return;
            }

        }

        public ActionResult UserView()
        {
            
            UserViewModel usermodel = new UserViewModel();
            if (Session["ParentId"] != null)
                usermodel.ParentId = Convert.ToInt32(Session["ParentId"]);
            else 
                usermodel.ParentId = 0;
            
            return View(usermodel);
        }

        [HttpPost]
        public ActionResult UserView(UserViewModel userviewmodel)
        {          
            using (var userinfo = new ABC_ClientEntities1())
            {
                var uinfo = (from u in userinfo.Users
                                    where u.UserId == userviewmodel.UserID
                                    select u).FirstOrDefault();
                if (uinfo != null)
                {
                    ModelState.AddModelError("UserId", "O ID do usuário já existe.");
                    return View(userviewmodel);                  
                }
            }
            if (userviewmodel.User_Password != userviewmodel.Reenter_Password)
            {
                ModelState.AddModelError("User_Password", "As senhas não correspondem");
                return View(userviewmodel);
            }
            User user = new User();
            user.Client = db.Clients.Find(userviewmodel.ParentId);
            user.Name = userviewmodel.ContactName;
            user.UserId = userviewmodel.UserID;
            user.Password = userviewmodel.User_Password;
            user.Password_ExpireDate = DateTime.Now.AddMonths(3);
            Contact contact = new Contact();

            contact.CellPhone = userviewmodel.CellPhone;
            contact.ContactName = userviewmodel.ContactName;
            contact.ContactType = userviewmodel.ContactType;
            contact.Email = userviewmodel.Email;
            contact.Fax = userviewmodel.Fax;
            contact.Gender = userviewmodel.Gender;
            contact.Phone = userviewmodel.Phone;
            contact.Title = userviewmodel.Title;
            user.Contacts.Add(contact);
            db.Users.Add(user);

            db.SaveChanges();
            return RedirectToAction("Index", "Home");        
        }

        [HttpGet]
        public ActionResult UserProfile()
        {
            UserViewModel userview = new UserViewModel();
            ActiveUser AU = (ActiveUser)Session["ActiveUser"];
            User user = (from u in db.Users
                         where u.UserId == AU.UserId
                         select u).FirstOrDefault();
            Contact cont = user.Contacts.FirstOrDefault();
            Common.CopyProperties(cont, userview, false);
            //Address addr = cont.Addresses.FirstOrDefault();
            //Common.CopyProperties(addr, userview.Address, false);
            userview.Id = user.Id;
            return View(userview);
        }


        [HttpPost]
        public ActionResult UserProfile(UserViewModel userview)
        {
            
            ActiveUser AU = (ActiveUser)Session["ActiveUser"];
            User user = (from u in db.Users
                         where u.UserId == AU.UserId
                         select u).FirstOrDefault();

src/Controllers/MailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Estoque_Rodrigo.Models;
using ClientDB;
using CATRAN_Mail;

namespace Estoque_Rodrigo.Controllers
{
    public class MailController : Controller
    {
        private Estoque_RodrigoClientEntities1 db = new ABC_ClientEntities1();
        // GET: Contact
        public ActionResult MailView()
        {
            MailViewModel cvm = new MailViewModel();
            return View(cvm);
        }
        [HttpPost]
        public ActionResult MailView(MailViewModel cvm)
        {
            ContactHistory ch = new ContactHistory();
            Common.CopyProperties(cvm, ch, false);
            ch.ContactDate = DateTime.Now;
            db.ContactHistories.Add(ch);
            string Message = "";
            Message += "Data:" + ch.ContatoData + "\n\r";
            Message += "Empresa,: " + ch.Empresa + "\n\r";
            Message += "Nome: " + ch.ContatoNome + "\n\r";
            Message += "Telefone: " + ch.Telefone + "\n\r";
            Message += "Email: " + ch.Email + "\n\r";
            Message += "Mensagem: " + ch.Comentarios + "\n\r";
            Class_Gmail mail = new Class_Gmail(ch.Email, ch.ContactName, "hjh@gmail.com", "Customer Service", "hjh@gmail.com", "hjh");
            mail.Subject = "Inquiry";
            mail.Body = Message;      
            mail.Send();      
            db.SaveChanges();
            return View(cvm);
        }
    }
}

src/Views/Shared/_Address.cshtml
@model Estoque_Rodrigo.Models.AddressViewModel

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.Label("Endereco:", htmlAttributes: new { @class = "control-label col-md-2" })
 
           <div class="col-md-9">
                @Html.EditorFor(model => model.Endereco1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Endereco1, "*", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label(" ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Endereco2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Endereco2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("City:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "*", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("State:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "*", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Province:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Country:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pais, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pais, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("CEP:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CEP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CEP, "*", new { @class = "text-danger" })
            </div>
        </div>

    </div>
@*}*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -ABC Inventory Management System</title>
     @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    <link href="@Url.Content("~/Content/jquery-ui.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-ui-1.10.0.min.js")" type="text/javascript"></script>

</head>
<body>
    <!-- Google Tag Manager -->
    <noscript>
        <iframe src="//www.googletagmanager.com/ns.html?id=GTM-MDB45S"
                height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <script>
(function (w, d, s, l, i) {
w[l] = w[l] || []; w[l].push({
'gtm.start':
new Date().getTime(), event: 'gtm.js'
}); var f = d.getElementsByTagName(s)[0],
j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
'//www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
})(window, document, 'script', 'dataLayer', 'GTM-MDB45S');</script>
    <!-- End Google Tag Manager -->

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
              
            </div>
           
            @{ABC_Inventory.Models.ActiveUser UserProps = (ABC_Inventory.Models.ActiveUser)Session["ActiveUser"];}

            <div class="navbar-collapse collapse">
                 <ul class="nav navbar-nav">
                     <li><a href="@Url.Action("Index", "Home")" >
                             <img src="~/Images/ABClogo.png" height="60" /> </a></li>
                    
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                @if (UserProps == null)
                {

                    <li>@Html.ActionLink("About Us", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact Us", "MailView", "Mail")</li>
                }                             

                @if (UserProps != null)
                { 
                     <li class="dropdown">
                         <a href="#" class="dropdown-toggle" id="dropdownCommonMenu" data-toggle="dropdown">Maintenance</a>
                         <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownCommonMenu">
                             
                             <li role="menuitem">@Html.ActionLink("Client Profile", "ClientProfile", "Clients")</li>
                             <li role="menuitem">@Html.ActionLink("User Profile", "UserProfile", "Clients")</li>

                             <li role="menuitem">@Html.ActionLink("Download Center", "Download", "Clients")</li>                        
                             <li role="menuitem">@Html.ActionLink("Licensing Manager", "", "")</li>
                             
                         </ul>
                     </li>                                                         
                }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
      
    </div> 
    @*<footer>*@
    <br/>
    <div class="container ">
        <ul class="nav navbar-nav">
            <li class="nav-text">
                &copy; @DateTime.Now.Year - ABC-Inventory.com
            </li>
        </ul>
        <ul class="nav navbar-nav  navbar-right">
            <li>
                @Html.ActionLink("About Us", "About", "Home")
            </li>
            <li>
                @Html.ActionLink("Contact Us", "MailView", "Mail")
            </li>
            <li>
                @Html.ActionLink("Privacy Policy", "PrivacyPolicy", "Home")
            </li>
            <li>
                @Html.ActionLink("Terms of Service", "TermsOfUse", "Home")
            </li>
        </ul>
    </div>
@*</footer>*@



    @RenderSection("scripts", required: false)
</body>
</html>

src/Views/Shared/_Public.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

src/Views/Shared/_Users.cshtml
@model Estoque_Rodrigo.Users


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Primary User Login</h4>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.Label("ID:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Senha:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
            </div>
        </div>

 
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}